<a href="https://colab.research.google.com/github/hekmat-ashqer/data_science_basics/blob/main/Intro_to_Pandas_DataFrames_cells.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create list of bake sale names
names_list = ['brownie','cookie','cake', 'cupcake']
names_list



[2.25, 1.25, 9.5, 3.5]

In [ ]:
# Create a list of prices
prices_list = [2.25,1.25,9.5, 3.5]
prices_list

[2.25, 1.25, 9.5, 3.5]

In [ ]:
# Define a list with the quantity sold
quantities_sold_list = [17, 40, 1, 10]
print(quantities_sold_list)

[17, 40, 1, 10]


In [ ]:
# import numpy
import numpy as np
# make a numpy array from the prices list
prices_array = np.array(prices_list)
prices_array

array([2.25, 1.25, 9.5 , 3.5 ])

In [ ]:
# make a numpy array from the quantities sold list
quantities_sold_array = np.array(quantities_sold_list)
quantities_sold_array

array([17, 40,  1, 10])

In [ ]:
# Find the length of the prices list
len(prices_list)

4

In [ ]:
# Check the shape of the prices array
prices_array.shape

(4,)

In [ ]:
# Arrays perform operations elementwise
prices_array * quantities_sold_array

array([38.25, 50.  ,  9.5 , 35.  ])

In [ ]:

import pandas as pd



In [ ]:
# Make a dataframe from a dictionary
df = pd.DataFrame({'Name':names_list,
                   'Price':prices_list,
                   "Quantity Sold": quantities_sold_list})
df



Name  Price  Quantity Sold
0  brownie   2.25             17
1   cookie   1.25             40
2     cake   9.50              1
3  cupcake   3.50             10

In [ ]:
# a special list with the names of each column
df.columns



Index(['Name', 'Price', 'Quantity Sold'], dtype='object')

In [ ]:
# the raw data in a numpy array
df.values

array([['brownie', 2.25, 17],
       ['cookie', 1.25, 40],
       ['cake', 9.5, 1],
       ['cupcake', 3.5, 10]], dtype=object)

In [ ]:
# Overwrite the original variable
df = df.set_index("Name")

In [ ]:
df

Price  Quantity Sold
Name                         
brownie   2.25             17
cookie    1.25             40
cake      9.50              1
cupcake   3.50             10

In [ ]:
# save the column as a new variable
sliced = df['Price']
sliced

Name
brownie    2.25
cookie     1.25
cake       9.50
cupcake    3.50
Name: Price, dtype: float64

In [ ]:
# This is a pandas series
type(sliced)

pandas.core.series.Series

In [ ]:
# Select one column using double brackets returns a DataFrame
df_slice = df[['Price']]
df_slice

Price
Name          
brownie   2.25
cookie    1.25
cake      9.50
cupcake   3.50

In [ ]:
# This is a pandas DataFrame
type(df_slice)

pandas.core.frame.DataFrame

In [ ]:
# Select multiple columns using double brackets
df[['Quantity Sold', 'Price']]

Quantity Sold  Price
Name                         
brownie             17   2.25
cookie              40   1.25
cake                 1   9.50
cupcake             10   3.50

In [ ]:
# Slicing columns using a variable
cols_to_slice = ['Quantity Sold', 'Price']
df[cols_to_slice]

Quantity Sold  Price
Name                         
brownie             17   2.25
cookie              40   1.25
cake                 1   9.50
cupcake             10   3.50

In [ ]:
# Find the shape of the dataframe
df.shape

(4, 2)

In [ ]:
# Series have a .name attribute
sliced

Name
brownie    2.25
cookie     1.25
cake       9.50
cupcake    3.50
Name: Price, dtype: float64

In [ ]:
df

Price  Quantity Sold  Sales  cost
Name                                      
brownie   2.25             17  38.25  0.25
cookie    1.25             40  50.00  0.50
cake      9.50              1   9.50  5.00
cupcake   3.50             10  35.00  0.75

In [ ]:
# Elementwise calculations with Pandas
sales = df['Price'] * df['Quantity Sold']
sales

Name
brownie    38.25
cookie     50.00
cake        9.50
cupcake    35.00
dtype: float64

In [ ]:
# saving sales as a new column
df['Sales'] = df['Price'] * df["Quantity Sold"]
df

Price  Quantity Sold  Sales
Name                                
brownie   2.25             17  38.25
cookie    1.25             40  50.00
cake      9.50              1   9.50
cupcake   3.50             10  35.00

In [ ]:
# Get the sum of the Sales column
df['Sales'].sum()

132.75

a brownie costs $0.25 to make.
a cookie costs $0.50 to make.
a cake costs $5.00 to make.
a cupcake costs $0.75 to make.

In [ ]:
# Making a series from a dictionary
expenses = pd.Series({'brownie':0.25, 'cookie':0.5, 'cake':5, 'cupcake': 0.75},
                     name='Expenses')
expenses

brownie    0.25
cookie     0.50
cake       5.00
cupcake    0.75
Name: Expenses, dtype: float64

In [ ]:
# saving our combined data as df
df = pd.concat([df, expenses], axis=1)
df

Price  Quantity Sold  Sales  Expenses
brownie   2.25             17  38.25      0.25
cookie    1.25             40  50.00      0.50
cake      9.50              1   9.50      5.00
cupcake   3.50             10  35.00      0.75

In [ ]:
df

Price  Quantity Sold  Sales  Expenses  Profit Per Item
brownie   2.25             17  38.25      0.25             2.00
cookie    1.25             40  50.00      0.50             0.75
cake      9.50              1   9.50      5.00             4.50
cupcake   3.50             10  35.00      0.75             2.75

In [ ]:
# Calculate profit and define it as new column
df['Profit Per Item'] = df['Price'] - df['Expenses']
df

In [ ]:
# Calculate the profit per type of baked good and define as a column
df["Profits"] = df['Profit Per Item'] * df['Quantity Sold']
df

Price  Quantity Sold  Sales  Expenses  Profit Per Item  Profits
brownie   2.25             17  38.25      0.25             2.00     34.0
cookie    1.25             40  50.00      0.50             0.75     30.0
cake      9.50              1   9.50      5.00             4.50      4.5
cupcake   3.50             10  35.00      0.75             2.75     27.5

In [ ]:
# Find total profit
total_profit = df['Profits'].sum()
total_profit

96.0

In [ ]:
# What percentage of the goal has been reached?
total_profit/1000

0.096